services:
    db:
      image: postgres
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=m@123456
        - POSTGRES_DB=MovieTracker
      ports:
        - "5433:5432"
      volumes:
        - ./postgres-data:/var/lib/postgresql/data
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        timeout: 5s
        retries: 5
    adminer:
      image: adminer
      restart: always
      ports:
      - 8080:8080
volumes:
  postgres-data:
